### ISSUE TITLE
Azure OpenAI not working with retrieval

### ISSUE THREAD

**Issue by abhiman23897** [langroid/langroid#309]
I am trying to use Azure OpenAI models with retrieval augmented doc chat. I have replaced the configs wherever I need by using AzureConfig. However, after doing this when I run examples/docqa/chat.py , I get this error only when relevance extractor is running, it works fine before that - 
2023-11-23 14:40:43 - ERROR - Error in OpenAIGPT.achat: 
Original error: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}
Traceback:
Traceback (most recent call last):
  File "langroid/language_models/openai_gpt.py", line 767, in achat
    result = await self._achat(messages, max_tokens, functions, function_call)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "langroid/language_models/openai_gpt.py", line 984, in _achat
    cached, hashed_key, response = await self._achat_completions_with_backoff(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "langroid/language_models/openai_gpt.py", line 817, in _achat_completions_with_backoff
    result = await acompletion_call(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "langroid/.venv/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 1199, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "langroid/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 1482, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "langroid/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 1283, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "langroid/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 1326, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

**To Reproduce**
1. Run the examples/docqa/chat.py without OpenAI api key, but with Azure open ai api key.

**Comment by pchalasani** [comment]
Thanks for reporting this. There is a special `AsyncAzureOpenAI()` client for async calls and we were not using it. 
Please upgrade to langroid 0.1.127
Also, in case you are not already doing it, please ensure you use `AzureConfig` in TWO places in the `DocChatAgentConfig` as shown below (since relevance extraction uses another agent to async + concurrently extract relevant text from chunks):

```
config = DocChatAgentConfig(
    ...
    llm = AzureConfig( ... ),
    ...
    relevance_extractor_config = (
        RelevanceExtractorAgentConfig(llm = AzureConfig( ... ))
    ),
    ...

Let us know if that doesn't fix it.

**Comment by Mohannadcse** [comment]
These are the imports that you need to make inside `docqa/chat.py`

```
from langroid.language_models.azure_openai import AzureConfig
from langroid.language_models.openai_gpt import OpenAIChatModel
from langroid.agent.special.relevance_extractor_agent import RelevanceExtractorAgentConfig
```

**Comment by abhiman23897** [comment]
Thank you. It seems to be working with the fix.
