### ISSUE TITLE
Illegal hardware instruction - There appear to be 1 leaked semaphore objects to clean up at shutdown

### ISSUE THREAD

**Issue by mneedham** [langroid/langroid#373]
Hi,

I tried to follow an example from the README and it's resulting in the Python process crashing. The code I ran is below:

```python
import langroid as lr
import langroid.language_models as lm
from langroid.language_models.base import LLMMessage, Role
from langroid.agent.special import DocChatAgentConfig, DocChatAgent
from langroid.embedding_models.models import SentenceTransformerEmbeddingsConfig

llm_cfg = lm.OpenAIGPTConfig(
    chat_model="ollama/mistral", 
    litellm=True
)
llm = lm.OpenAIGPT(llm_cfg)

config = DocChatAgentConfig(
  doc_paths = [
    "https://en.wikipedia.org/wiki/Language_model",
    "https://en.wikipedia.org/wiki/N-gram_language_model"
  ],
  vecdb=lr.vector_store.LanceDBConfig(
    embedding=SentenceTransformerEmbeddingsConfig()
  ),
)

agent = DocChatAgent(config)

agent.llm_response("What is a language model?")
```

I get the following output on the penultimate line

```bash
I have processed the following 2 URLs
        and 0 paths into 9 parts:
https://en.wikipedia.org/wiki/Language_model
https://en.wikipedia.org/wiki/N-gram_language_model
```

But then it crashes on the last line:

```bash
In [4]: agent.llm_response("What is a language model?")
⠹ Searching VecDB for relevant doc passages...[1]    52986 illegal hardware instruction  poetry run ipython
/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by pchalasani** [comment]
You have to set `chat_model  = "litellm/ollama/mistral"`. See docs here https://langroid.github.io/langroid/tutorials/non-openai-llms/
or simple local-LLM RAG example here: https://github.com/langroid/langroid-examples/blob/main/examples/docqa/rag-local-simple.py

**Comment by mneedham** [comment]
Ok - will try that. 

I should say that the code I have worked fine for some of the other examples e.g. this one works

```python
import langroid as lr
import langroid.language_models as lm
from langroid.language_models.base import LLMMessage, Role

llm_cfg = lm.OpenAIGPTConfig(
    chat_model="ollama/mistral", 
    litellm=True
)
llm = lm.OpenAIGPT(llm_cfg)
llm.chat("What is 3+4?", max_tokens=10)
```

```text
2024-01-18 22:20:07 - WARNING - REDIS_PASSWORD, REDIS_HOST, REDIS_PORT not set in .env file,
                    using fake redis client
The sum of 3 and 4 is 7. So, 3 + 4 = 7. This is a basic arithmetic problem. In mathematics, addition is the process of combining two or more numbers to get a new number, which is called the sum. When you write down an addition problem like 3 + 4, it means that you want to find the result of adding 3 and 4 together. And as mentioned earlier, the answer is 7.
Out[1]:

LLMResponse(
    message='The sum of 3 and 4 is 7. So, 3 + 4 = 7. This is a basic arithmetic problem. In mathematics, addition is the process of combining two or more numbers to get a new number, which is called the sum. When you write down an addition problem like 3 + 4, it means that you want to find the result of adding 3 and 4 together. And as mentioned earlier, the answer is 7.',
    tool_id='',
    function_call=None,
    usage=None,
    cached=False
)
```

**Comment by mneedham** [comment]
It still crashes in the same way when I define the model with the `litellm` prefix

**Comment by pchalasani** [comment]
The code is fine. Your error looks like some transient error related to either the fact that you're running it in a notebook or some transient issue on your computer (e.g. maybe find and kill zombie python processes)

**Comment by mneedham** [comment]
I've tried using the iPython REPL, normal Python REPL, running it directly as a Python script. This is all with Poetry:

_single.py_
```python
import langroid as lr
import langroid.language_models as lm

from langroid.language_models.base import LLMMessage, Role
from langroid.agent.special import DocChatAgentConfig, DocChatAgent
from langroid.embedding_models.models import SentenceTransformerEmbeddingsConfig

llm_cfg = lm.OpenAIGPTConfig(
    chat_model="litellm/ollama/mistral"
)
llm = lm.OpenAIGPT(llm_cfg)



config = DocChatAgentConfig(
  doc_paths = [
    "https://en.wikipedia.org/wiki/Language_model",
    "https://en.wikipedia.org/wiki/N-gram_language_model"
  ],
  vecdb=lr.vector_store.LanceDBConfig(
    embedding=SentenceTransformerEmbeddingsConfig()
  ),
  llm=llm_cfg
)

agent = DocChatAgent(config)
agent.llm_response("What is a language model?")
```

So I switched over to venv

```
python -m venv .venv
source .venv/bin/activate

pip install langroid litellm
```

This time it does seem to make some progress, but I need to adjust my token limit:

```
config.json: 100%|######################################################################################################| 794/794 [00:00<00:00, 3.25MB/s]

pytorch_model.bin:   0%|                                                                                                     | 0.00/90.9M [00:00<?, ?B/s]
pytorch_model.bin:  12%|##########6                                                                                 | 10.5M/90.9M [00:00<00:06, 12.4MB/s]
pytorch_model.bin:  23%|#####################2                                                                      | 21.0M/90.9M [00:01<00:05, 11.9MB/s]
pytorch_model.bin:  35%|###############################8                                                            | 31.5M/90.9M [00:02<00:05, 10.5MB/s]
pytorch_model.bin:  46%|##########################################4                                                 | 41.9M/90.9M [00:03<00:04, 10.6MB/s]
pytorch_model.bin:  58%|#####################################################                                       | 52.4M/90.9M [00:04<00:03, 10.6MB/s]
pytorch_model.bin:  69%|###############################################################6                            | 62.9M/90.9M [00:05<00:02, 10.4MB/s]
pytorch_model.bin:  81%|##########################################################################2                 | 73.4M/90.9M [00:06<00:01, 10.9MB/s]
pytorch_model.bin:  92%|####################################################################################8       | 83.9M/90.9M [00:07<00:00, 10.9MB/s]
pytorch_model.bin: 100%|############################################################################################| 90.9M/90.9M [00:08<00:00, 11.6MB/s]
pytorch_model.bin: 100%|############################################################################################| 90.9M/90.9M [00:08<00:00, 11.1MB/s]

tokenizer_config.json:   0%|                                                                                                   | 0.00/316 [00:00<?, ?B/s]
tokenizer_config.json: 100%|############################################################################################| 316/316 [00:00<00:00, 1.23MB/s]

vocab.txt:   0%|                                                                                                              | 0.00/232k [00:00<?, ?B/s]
vocab.txt: 100%|######################################################################################################| 232k/232k [00:00<00:00, 1.33MB/s]
vocab.txt: 100%|######################################################################################################| 232k/232k [00:00<00:00, 1.31MB/s]

special_tokens_map.json:   0%|                                                                                                 | 0.00/112 [00:00<?, ?B/s]
special_tokens_map.json: 100%|###########################################################################################| 112/112 [00:00<00:00, 238kB/s]

2024-01-19 07:32:11 - WARNING - REDIS_PASSWORD, REDIS_HOST, REDIS_PORT not set in .env file,
                    using fake redis client
Traceback (most recent call last):
  File "/Users/markhneedham/projects/learndatawithmark/langroid-sandbox/single.py", line 27, in <module>
    agent.llm_response("What is a language model?")
  File "/Users/markhneedham/projects/learndatawithmark/langroid-sandbox/.venv/lib/python3.10/site-packages/langroid/agent/special/doc_chat_agent.py", line 534, in llm_response
    response = self.answer_from_docs(query_str)
  File "/Users/markhneedham/projects/learndatawithmark/langroid-sandbox/.venv/lib/python3.10/site-packages/langroid/agent/special/doc_chat_agent.py", line 1051, in answer_from_docs
    query, extracts = self.get_relevant_extracts(query)
  File "/Users/markhneedham/projects/learndatawithmark/langroid-sandbox/.venv/lib/python3.10/site-packages/langroid/agent/special/doc_chat_agent.py", line 980, in get_relevant_extracts
    extracts = self.get_verbatim_extracts(query, passages)
  File "/Users/markhneedham/projects/learndatawithmark/langroid-sandbox/.venv/lib/python3.10/site-packages/langroid/agent/special/doc_chat_agent.py", line 1019, in get_verbatim_extracts
    extracts = run_batch_tasks(
  File "/Users/markhneedham/projects/learndatawithmark/langroid-sandbox/.venv/lib/python3.10/site-packages/langroid/agent/batch.py", line 66, in run_batch_tasks
    results = asyncio.run(_do_all())
  File "/Users/markhneedham/miniforge3/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/markhneedham/miniforge3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/markhneedham/projects/learndatawithmark/langroid-sandbox/.venv/lib/python3.10/site-packages/langroid/agent/batch.py", line 58, in _do_all
    return await asyncio.gather(
  File "/Users/markhneedham/projects/learndatawithmark/langroid-sandbox/.venv/lib/python3.10/site-packages/langroid/agent/batch.py", line 53, in _do_task
    result = await task_i.run_async(input)
  File "/Users/markhneedham/projects/learndatawithmark/langroid-sandbox/.venv/lib/python3.10/site-packages/langroid/agent/task.py", line 434, in run_async
    await self.step_async()
  File "/Users/markhneedham/projects/learndatawithmark/langroid-sandbox/.venv/lib/python3.10/site-packages/langroid/agent/task.py", line 641, in step_async
    result = await self.response_async(r, turns)
  File "/Users/markhneedham/projects/learndatawithmark/langroid-sandbox/.venv/lib/python3.10/site-packages/langroid/agent/task.py", line 831, in response_async
    result = await response_fn(self.pending_message)
  File "/Users/markhneedham/projects/learndatawithmark/langroid-sandbox/.venv/lib/python3.10/site-packages/langroid/agent/special/relevance_extractor_agent.py", line 100, in llm_response_async
    return await super().llm_response_async(prompt)
  File "/Users/markhneedham/projects/learndatawithmark/langroid-sandbox/.venv/lib/python3.10/site-packages/langroid/agent/chat_agent.py", line 474, in llm_response_async
    hist, output_len = self._prep_llm_messages(message)
  File "/Users/markhneedham/projects/learndatawithmark/langroid-sandbox/.venv/lib/python3.10/site-packages/langroid/agent/chat_agent.py", line 571, in _prep_llm_messages
    raise ValueError(
ValueError:
                        The message history is longer than the max chat context
                        length allowed, and we have run out of messages to drop.
                        HINT: In your `OpenAIGPTConfig` object, try increasing
                        `chat_context_length` or decreasing `max_output_tokens`.
```

So maybe some sort of issue with using Poetry?

```bash
poetry run python single.py
2024-01-19 07:23:48 - WARNING - REDIS_PASSWORD, REDIS_HOST, REDIS_PORT not set in .env file,
                    using fake redis client
2024-01-19 07:23:48 - WARNING - REDIS_PASSWORD, REDIS_HOST, REDIS_PORT not set in .env file,
                    using fake redis client
2024-01-19 07:23:58 - WARNING - Non-empty Collection temp already exists
2024-01-19 07:23:58 - WARNING - Not replacing collection
I have processed the following 2 URLs
        and 0 paths into 9 parts:
https://en.wikipedia.org/wiki/Language_model
https://en.wikipedia.org/wiki/N-gram_language_model

⠹ Searching VecDB for relevant doc passages...[1]    53790 illegal hardware instruction  poetry run python single.py
/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by pchalasani** [comment]
The leaked semaphore error could be related to the sentence transformer embeddings. If you switch to openai embeddings it may disappear. 
The last run looks fine, you just have to set the `chat_context_length = 4096` or similar.

Poetry shouldn't cause an issue.

**Comment by mneedham** [comment]
Oh could be yeh. I was seeing if I could run everything on my machine, that's why I'd switching to HF embeddings. Maybe my transformers installation went wrong though. I will explore.

I kinda wanna use FastEmbed for the embeddings, as it's much lighter weight than transformers, so maybe I'll try to do a PR to add that to the library.

**Comment by pchalasani** [comment]
A FastEmbed PR would be great! I like that it has no PyTorch dependency

**Comment by pchalasani** [comment]
Closing, let me know if this issue lingers.
