### ISSUE TITLE
openai.AuthenticationError - OpenAI API key needed to access DocChatAgent using Ollama?

### ISSUE THREAD

**Issue by Solonce** [langroid/langroid#442]
As title states, I keep getting an error saying that I have an invalid API key. Which, is true, but I'm not using OpenAI models, I'm using Ollama. This is what my code looks like:

```python
import langroid as lr
import langroid.language_models as lm
from langroid.agent.special import DocChatAgentConfig, DocChatAgent

llm_config = lm.OpenAIGPTConfig(
	chat_model="ollama/mistral",
	chat_context_length=4096,
	ollama=True
)

config = DocChatAgentConfig(
  llm=llm_config,
  doc_paths = [
    "https://en.wikipedia.org/wiki/Language_model",
    "https://en.wikipedia.org/wiki/N-gram_language_model",
  ],
  vecdb=lr.vector_store.LanceDBConfig(),
)


agent = DocChatAgent(config)

task = lr.Task(agent)
task.run()
```

Additionally, I also run this variation of ```OpenAIGPTConfig```, but the same error persisted.

```python
llm_config = lm.OpenAIGPTConfig(
	type="ollama",
	chat_model="ollama/mistral",
	api_base="localhost:11434",
	api_key="",
	chat_context_length=4096,
	ollama=True
)
```

Here is the error I'm encountering:

```
Traceback (most recent call last):
  File "/home/solomon/Documents/langroid/test.py", line 26, in <module>
    agent = DocChatAgent(config)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/solomon/Documents/langroid/langroid/lib/python3.11/site-packages/langroid/agent/special/doc_chat_agent.py", line 208, in __init__
    self.ingest()
  File "/home/solomon/Documents/langroid/langroid/lib/python3.11/site-packages/langroid/agent/special/doc_chat_agent.py", line 252, in ingest
    self.ingest_doc_paths(self.config.doc_paths)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/solomon/Documents/langroid/langroid/lib/python3.11/site-packages/langroid/agent/special/doc_chat_agent.py", line 335, in ingest_doc_paths
    n_splits = self.ingest_docs(docs, split=self.config.split)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/solomon/Documents/langroid/langroid/lib/python3.11/site-packages/langroid/agent/special/doc_chat_agent.py", line 419, in ingest_docs
    self.vecdb.add_documents(batch)
  File "/home/solomon/Documents/langroid/langroid/lib/python3.11/site-packages/langroid/vector_store/lancedb.py", line 260, in add_documents
    embedding_vecs = self.embedding_fn([doc.content for doc in documents])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/solomon/Documents/langroid/langroid/lib/python3.11/site-packages/langroid/embedding_models/models.py", line 81, in __call__
    result = self.model.client.embeddings.create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/solomon/Documents/langroid/langroid/lib/python3.11/site-packages/openai/resources/embeddings.py", line 113, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/solomon/Documents/langroid/langroid/lib/python3.11/site-packages/openai/_base_client.py", line 1213, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/solomon/Documents/langroid/langroid/lib/python3.11/site-packages/openai/_base_client.py", line 902, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/solomon/Documents/langroid/langroid/lib/python3.11/site-packages/openai/_base_client.py", line 993, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: your-key***************uote. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
```

Here's the ```openai.AuthenticationError```
```
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: your-key***************uote. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
```

It's also worth noting, I printed out ```config.llm``` and ```llm_config``` and both showed ```chat_model="ollama/mistral"```, but it's definitely pulling that API key from the ```.env``` file. Just not sure why or how to avoid.

Thanks

**Comment by Solonce** [comment]
I've narrowed down the issue a bit.

It appears to be when ```doc_path``` or ```default_path``` paths are used. It also appears to throw an error, even with local files. I don't include ```doc_path``` and just rely on ```default_path``` the same error is thrown, even if the ```default_path``` array has one entry that is just a path to a local file.

**Comment by pchalasani** [comment]
The error trace shows it’s using OpenAI API for embeddings, hence the need for a valid key. See this example for how to instead use sentence transformer embeddings: https://github.com/langroid/langroid/blob/main/examples/docqa/chat.py
