### ISSUE TITLE
Add Azure embeddings

### ISSUE THREAD

**Issue by pchalasani** [langroid/langroid#514]
Implementation should be similar to the OpenAI embeddings

**Comment by AbhishekRP2002** [comment]
hi @pchalasani  if this issue is still open, I would love to take this up!
I believe this will be a good reference to get started: https://github.com/langroid/langroid/blob/main/langroid/embedding_models/models.py

and this : https://learn.microsoft.com/en-us/azure/ai-services/openai/reference

**Comment by pchalasani** [comment]
> would love to take this up!

Sure, @AbhishekRP2002 sounds good

**Comment by AbhishekRP2002** [comment]
@pchalasani  got the following error while installing dependencies:

```
❯ poetry install --with dev
Installing dependencies from lock file

Package operations: 40 installs, 0 updates, 0 removals

  - Installing mysqlclient (2.2.4): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  /bin/sh: pkg-config: command not found
  /bin/sh: pkg-config: command not found
  /bin/sh: pkg-config: command not found
  Trying pkg-config --exists mysqlclient
  Command 'pkg-config --exists mysqlclient' returned non-zero exit status 127.
  Trying pkg-config --exists mariadb
  Command 'pkg-config --exists mariadb' returned non-zero exit status 127.
  Trying pkg-config --exists libmariadb
  Command 'pkg-config --exists libmariadb' returned non-zero exit status 127.
  Traceback (most recent call last):
    File "/Users/abhishekrp/.local/pipx/venvs/poetry/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
      main()
    File "/Users/abhishekrp/.local/pipx/venvs/poetry/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/abhishekrp/.local/pipx/venvs/poetry/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/16/59hrdlv17s3cwj7my3h0cfhr0000gn/T/tmpf905d1w3/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/16/59hrdlv17s3cwj7my3h0cfhr0000gn/T/tmpf905d1w3/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 303, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/16/59hrdlv17s3cwj7my3h0cfhr0000gn/T/tmpf905d1w3/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 319, in run_setup
      exec(code, locals())
    File "<string>", line 155, in <module>
    File "<string>", line 49, in get_config_posix
    File "<string>", line 28, in find_package_name
  Exception: Can not find valid pkg-config name.
  Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually
  

  at ~/.local/pipx/venvs/poetry/lib/python3.13/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with mysqlclient (2.2.4) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "mysqlclient (==2.2.4)"'.

```
can u pls help me out in debugging this ?
any help or ref will be highly appreciated.

**Comment by AbhishekRP2002** [comment]
yeah seems like it. however, i got these 2 errors in the `make tests` command output:

```
====================================== short test summary info ======================================
ERROR tests/main/test_momento_cache.py
ERROR tests/main/sql_chat/test_sql_chat_agent.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================== 29 warnings, 2 errors in 4.34s ===================================
make: *** [tests] Error 2
```
I have also added a fix for `ruff` command used for lining / style checking:
previously it was `poetry run ruff . --fix` which was wrong I believe
I updated it to `poetry run ruff check . --fix` 

cc: @pchalasani

**Comment by AbhishekRP2002** [comment]
NVM, got it fixed, I had to install integration packages for langroid supporting the corresponding packages, like `langroid[SQL] and langroid[moment]`

Pls lemme know if there any other review at your end.
and are you planning to add `async` support for `openai / azure openai embedding model` ?
If yes, I would love to update the code with incremental changes @pchalasani

**Comment by pchalasani** [comment]
Thanks @AbhishekRP2002 I will review in a day or two, and I'll decide about async after.

**Comment by AbhishekRP2002** [comment]
Sounds good. Thank you

**Comment by pchalasani** [comment]
closing, done in PR #651
