### ISSUE TITLE
Fails with QdrandDBConfig validation error at import langroid

### ISSUE THREAD

**Issue by tanjucat** [langroid/langroid#594]
**Describe the bug**

after installing `langroid[all]` any script fails with QdrantDBConfig() validation error.

**To Reproduce**
1. `conda create -n langroid python=3.11`
2. `conda activate langroid`
3. `pip install langroid[all]`
4. `echo "import langroid as lr" > tutorial.py`
5. `echo 'print("hello world")' >> tutorial.py`
6. `rm -f .env` (to ensure that there is no .env in the directory)
7. `python tutorial.py`

**Expected behavior**
It prints
```
/opt/homebrew/Caskroom/miniconda/base/envs/langroid/lib/python3.11/site-packages/pypdf/_crypt_providers/_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from this module in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4
Traceback (most recent call last):
  File "/[..]/Development/langroid/tutorial.py", line 1, in <module>
    import langroid as lr
  File "/opt/homebrew/Caskroom/miniconda/base/envs/langroid/lib/python3.11/site-packages/langroid/__init__.py", line 15, in <module>
    from . import vector_store
  File "/opt/homebrew/Caskroom/miniconda/base/envs/langroid/lib/python3.11/site-packages/langroid/vector_store/__init__.py", line 3, in <module>
    from . import qdrantdb
  File "/opt/homebrew/Caskroom/miniconda/base/envs/langroid/lib/python3.11/site-packages/langroid/vector_store/qdrantdb.py", line 76, in <module>
    class QdrantDB(VectorStore):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/langroid/lib/python3.11/site-packages/langroid/vector_store/qdrantdb.py", line 77, in QdrantDB
    def __init__(self, config: QdrantDBConfig = QdrantDBConfig()):
                                                ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/langroid/lib/python3.11/site-packages/pydantic/v1/env_settings.py", line 40, in __init__
    super().__init__(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/langroid/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for QdrantDBConfig
docker
  value could not be parsed to a boolean (type=type_error.bool)
```

**Desktop (please complete the following information):**
 - OS: macOS 15.0.1
 
**Additional context**

**Comment by tanjucat** [comment]
A follow up:
Exact same steps do nor reproduce the problem on linux (CentOS 7)

Note: macOS mentioned in the original report is running on Apple silicon.

**Comment by pchalasani** [comment]
@tanjucat I tried it as follows in a clean venv and don't see the error:

```bash
cd /tmp
mkdir test
python3 -m venv .venv
. ./.venv/bin/activate
# uses python 3.12, but 3.11 should be similar
pip install langroid[all]
cat > try.py
import langroid as lr
print("hi")

python3 try.py
```

The issue may be related to something specific conda is doing (I don't use conda, and recommend venv instead). A similar pydantic error was reported here (unrelated to conda), and it had something to do with the environment:

https://github.com/pydantic/pydantic/issues/3521

**Comment by pchalasani** [comment]
@tanjucat This is puzzling. Could you paste the error trace please?

**Comment by tanjucat** [comment]
These are the steps I followed:
```
$ mkdir test
$ cd test
$ python3.11 -mvenv env.lr
$ source env.lr/bin/activate
$ pip3.11 install langroid[all]
$ cat > try.py
import langroid as lr
print("hi")

$ python3.11 -m pip list | grep pydan
pydantic                                 2.9.2
pydantic_core                            2.23.4

$ python3.11 try.py
/Users/[...]/test/env.lr/lib/python3.11/site-packages/pypdf/_crypt_providers/_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from this module in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4
Traceback (most recent call last):
  File "/Users/[...]/test/try.py", line 1, in <module>
    import langroid as lr
  File "/Users/[...]/test/env.lr/lib/python3.11/site-packages/langroid/__init__.py", line 15, in <module>
    from . import vector_store
  File "/Users/[...]/test/env.lr/lib/python3.11/site-packages/langroid/vector_store/__init__.py", line 3, in <module>
    from . import qdrantdb
  File "/Users/[...]/test/env.lr/lib/python3.11/site-packages/langroid/vector_store/qdrantdb.py", line 76, in <module>
    class QdrantDB(VectorStore):
  File "/Users/[...]/test/env.lr/lib/python3.11/site-packages/langroid/vector_store/qdrantdb.py", line 77, in QdrantDB
    def __init__(self, config: QdrantDBConfig = QdrantDBConfig()):
                                                ^^^^^^^^^^^^^^^^
  File "/Users/[...]/test/env.lr/lib/python3.11/site-packages/pydantic/v1/env_settings.py", line 40, in __init__
    super().__init__(
  File "/Users/[...]/test/env.lr/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for QdrantDBConfig
docker
  value could not be parsed to a boolean (type=type_error.bool)
```

**Comment by pchalasani** [comment]
I have the exact same pydantic versions, and I even stepped through the debugger, and it goes to exactly the line numbers in your trace until `env_settings.py`, and then in `v1/main.py`, the validation succeeds (unlike in your trace).

**Comment by pchalasani** [comment]
Closing due to lack of response.
